language: go
go:
  - "1.13"

env:
  - GO111MODULE=on

go_import_path: github.com/chanzuckerberg/terraform-provider-snowflake

install:
  # - npm install -g snyk
  - make setup

script:
  - make

matrix:
  include:
    - name: unit/acceptance tests
      script:
        - make test-acceptance-ci
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    # Disable snyk until https://github.com/snyk/snyk/issues/354 is resolved
    # - name: snyk
    #   script:
    #     - snyk monitor --org=czi
    #     - snyk test
    - name: docs check
      script:
        - make check-docs
    - name: modules check
      script:
        - make check-mod
    - name: linter check
      script:
        - make lint-ci
