# Validates PR title follows conventional commits
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - reopened

jobs:
  conventional_commit_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const validator = /^(chore|feat|fix|revert|docs|style)(\([a-z ]+\))?(!)?: (.)+$/
            const title = context.payload.pull_request.title
            const is_valid = validator.test(title)

            if (!is_valid) {
              const details = JSON.stringify({
                title: title,
                valid_syntax: validator.toString(),
              })

              core.setFailed(`Your pr title doesn't adhere to conventional commits syntax. See more details: ${details}`)
            }
